<?php
/**
 * Catalog of the paid features, generated by bin/gen-pro-catalog.php.
 *
 * Do not edit by hand: run the generator instead.
 *
 * @package XODW\CalendarCore
 */

defined( 'ABSPATH' ) || exit;

return array(
	array(
		'slug'  => 'tickets',
		'title' => __( 'Ticket sales', 'calendarcore' ),
		'blurb' => __( 'Stripe Checkout or your WooCommerce cart, ticket types, seat limits, promo codes and ticket codes at the door.', 'calendarcore' ),
	),
	array(
		'slug'  => 'reminders',
		'title' => __( 'Email and SMS reminders', 'calendarcore' ),
		'blurb' => __( 'Automatic reminders 24 hours and 1 hour before the event, with your own templates and your own SMS provider.', 'calendarcore' ),
	),
	array(
		'slug'  => 'google',
		'title' => __( 'Google Calendar sync', 'calendarcore' ),
		'blurb' => __( 'Two way synchronisation over the official API, recurring series included.', 'calendarcore' ),
	),
	array(
		'slug'  => 'submission',
		'title' => __( 'Front end submission', 'calendarcore' ),
		'blurb' => __( 'Visitors propose events, you approve them. Honeypot and rate limit instead of a captcha.', 'calendarcore' ),
	),
	array(
		'slug'  => 'organizers',
		'title' => __( 'Multiple organizers', 'calendarcore' ),
		'blurb' => __( 'A dedicated role where each organizer sees and edits only their own events.', 'calendarcore' ),
	),
	array(
		'slug'  => 'analytics',
		'title' => __( 'Analytics', 'calendarcore' ),
		'blurb' => __( 'Views, RSVP conversion and ticket revenue, counted on your own server.', 'calendarcore' ),
	),
);
